name: Test deployment

# CINTENT >> MANUAL_TRIGGER
# on:
#   pull_request:
#     # Review gh actions docs if you want to further define triggers, paths, etc
#     # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
on: [repository_dispatch, workflow_dispatch]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # CINTENT >> INSERT_CINTENT
      - uses: JavidDitty/setup-cintent@a606c80c34ec190c6a20dea33d6d58ddb6c4e0cc

      - name: Setup / build docs
        run: |
          sudo chmod -R 777 .
          python3 -m pip install --upgrade pip --progress-bar off
          python3 -m pip install -e .[dev] --progress-bar off
          python3 -m pip install beautifulsoup4 ipython jinja2==3.0.0 nbconvert==5.6.1 ipython_genutils --progress-bar off
          ./scripts/build_docs.sh -b
          cd website

      # CINTENT >> INSERT_CINTENT
      - name: Upload CIntent Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ env.CINTENT_ARTIFACT_NAME }}
          path: ${{ env.CINTENT_LOGS }}
